version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: ./mvnw install
      - run:
          name: Run tests
          command: ./mvnw test
      - run:
          name: Build project
          command: ./mvnw package

workflows:
  version: 2
  build_and_test:
    jobs:
      - build